import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
} from "react";

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

const translations = {
  en: {
    // Navigation
    nav: {
      home: "Home",
      forYou: "For You",
      newArrivals: "New Arrivals",
      popular: "Popular",
      sale: "Sale",
      disputes: "Disputes",
      qrScanner: "QR Scanner",
      categories: "Categories",
      downloadApp: "Download App",
      support: "Support",
      about: "About MegaMart",
      favorites: "Favorites",
      cart: "Cart",
      notifications: "Notifications",
      profile: "Profile",
      logout: "Logout",
      contact: "Contact Seller",
      becomeSeller: "Become Seller",
      signIn: "Sign In",
      signUp: "Sign Up",
      seller: "Seller",
      admin: "Admin",
      allCaughtUp: "All caught up",
      markAll: "Mark all",
      unread: "unread",
    },
    // Auth
    auth: {
      welcome: "Welcome",
      megaMart: "MegaMart",
      welcomeSubtitle: "Welcome! Please enter your account.",
      signInTitle: "Sign In",
      signUpTitle: "Please enter your details.",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      firstName: "First Name",
      lastName: "Last Name",
      phone: "Phone",
      userType: "User Type",
      buyer: "Buyer",
      seller: "Seller",
      agreeTerms: "I agree to the Terms and Conditions",
      getNews: "I want to receive news and offers",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      signInHere: "Sign In here",
      signUpHere: "Sign Up here",
      developer: "Developed",
      contact: "Contact",
      by: "By",
    },
    // Home
    home: {
      welcome: "Welcome to Our Store",
      discover: "Discover amazing products at great prices",
      shopNow: "Shop Now",
      fastShipping: "Fast Shipping",
      freeShipping: "Free shipping on orders over $100",
      securePayment: "Secure Payment",
      safePayment: "Safe and secure payment processing",
      support24: "24/7 Support",
      roundClock: "Round-the-clock customer support",
    },
    // Products
    products: {
      title: "Our Products",
      inStock: "In Stock",
      outOfStock: "Out of Stock",
      addToCart: "Add to Cart",
      addedToCart: "Added to Cart!",
      addToFavorites: "Add to favorites",
      removeFromFavorites: "Remove from favorites",
      freeShipping: "Free Shipping",
      easyReturns: "Easy Returns",
      securePayment: "Secure Payment",
      price: "Price",
      quantity: "Quantity",
      description: "Description",
      reviews: "Reviews",
      relatedProducts: "Related Products",
      noProducts: "No products found",
      searchPlaceholder: "Search products, brands, categories...",
      filters: "Filters",
      hideFilters: "Hide Filters",
      sort: "Sort",
      perPage: "Per Page",
      inStockOnly: "In stock only",
      viewDetails: "View Details",
      saleBadgeShort: "Sale",
      saleActiveLabel: "Limited-time price",
      newArrival: "New arrival",
      sortNewest: "Newest",
      sortOldest: "Oldest",
      sortPriceLow: "Price: Low to High",
      sortPriceHigh: "Price: High to Low",
      sortNameAsc: "Name: A-Z",
      sortNameDesc: "Name: Z-A",
      sortPopular: "Most Popular",
      sortSale: "On Sale",
      sortForYou: "For You",
      context: {
        saleTitle: "Spotlight Deals",
        saleText:
          "Curated discounts from sellers currently running promotions.",
        popularTitle: "Trending Now",
        popularText: "Based on recent purchases, views, and shopper favorites.",
        newTitle: "Fresh Arrivals",
        newText: "Recently published products from trusted sellers.",
        newFallbackText:
          "No brand-new products this week, showing the latest instead.",
        forYouTitle: "Just for you",
        forYouText: "Personalized picks inspired by your recent activity.",
        forYouFallback:
          "You're seeing popular picks while we learn your tastes.",
      },
    },
    // Cart
    cart: {
      title: "Shopping Cart",
      empty: "Your cart is empty",
      continueShopping: "Continue Shopping",
      subtotal: "Subtotal",
      total: "Total",
      checkout: "Proceed to Checkout",
      remove: "Remove",
      update: "Update",
    },
    // Checkout
    checkout: {
      title: "Checkout",
      shippingInfo: "Shipping Information",
      paymentMethod: "Payment Method",
      orderSummary: "Order Summary",
      placeOrder: "Place Order",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      city: "City",
      state: "State/Region",
      zipCode: "ZIP Code",
      country: "Country",
      orderNotes: "Order Notes",
      paymentInstructions: "Payment Instructions",
      manualPayment: "Manual Payment",
      sendPaymentTo: "Send payment to",
      enterTransactionId: "Enter the transaction ID below after payment",
      transactionId: "Transaction ID",
      secureCheckout: "Secure checkout with SSL encryption",
      addProductsFirst: "Add some products to your cart before checkout.",
    },
    // Orders
    orders: {
      orderId: "Order ID",
      orderNumber: "Order Number",
      orderNumberShort: "Order #",
      orderDate: "Order Date",
      orderStatus: "Order Status",
      orderDetails: "Order Details",
      orderItems: "Order Items",
      orderSummary: "Order Summary",
      shippingAddress: "Shipping Address",
      orderNotes: "Order Notes",
      paymentMethod: "Payment Method",
      quantity: "Quantity",
      quantityShort: "Qty",
      subtotal: "Subtotal",
      tax: "Tax",
      shipping: "Shipping",
      total: "Total",
      downloadReceipt: "Download Receipt",
      generatingReceipt: "Generating...",
      continueShopping: "Continue Shopping",
      viewProfile: "View Profile",
      viewReceipt: "View Receipt",
      emailConfirmation: "You will receive an email confirmation shortly.",
      confirmedTitle: "Order Confirmed!",
      confirmedMessage:
        "Thank you for your order. We've received it and will process it shortly.",
      notFound: "Order not found",
      notFoundDescription: "The order you're looking for doesn't exist.",
      goHome: "Go Home",
      backToOrders: "Back to Orders",
      orderTracking: "Order Tracking",
      currentStatus: "Current Status",
      downloadFailed: "Failed to download receipt. Please try again.",
      viewDetails: "View Details",
      trackOrder: "Track Order",
      orderIdPrefix: "Order",
      pending: "Pending",
      paid: "Paid",
      processing: "Processing",
      shipped: "Shipped",
      completed: "Completed",
      cancelled: "Cancelled",
      timeline: {
        orderPlaced: "Order Placed",
        pending: "Pending",
        paymentVerified: "Payment Verified",
        processing: "Processing",
        shipped: "Shipped",
        completed: "Completed",
        cancelled: "Cancelled",
      },
      paymentMethods: {
        telebirr: "Telebirr",
        paypal: "PayPal",
      },
    },
    // Disputes
    disputes: {
      title: "Disputes",
      createDispute: "Create Dispute",
      reason: "Reason",
      details: "Details",
      submit: "Submit",
      reply: "Reply",
      status: "Status",
      open: "Open",
      accepted: "Accepted",
      rejected: "Rejected",
      resolved: "Resolved",
      commonReasons: {
        paymentNotApproved: "Payment not approved in time",
        sellerNotDeliver: "Seller did not deliver",
        wrongItem: "Received wrong item",
        missingItem: "Item missing or incomplete",
        damagedItem: "Item arrived damaged",
        other: "Other",
      },
    },
    // Dashboard
    dashboard: {
      admin: "Admin Dashboard",
      seller: "Seller Dashboard",
      overview: "Overview",
      users: "Users",
      sellers: "Sellers",
      orders: "Orders",
      products: "Products",
      categories: "Categories",
      brands: "Brands",
      totalRevenue: "Total Revenue",
      totalOrders: "Total Orders",
      totalProducts: "Total Products",
      itemsShipped: "Items Shipped",
      netEarnings: "Net Earnings",
      gross: "Gross",
    },
    // Profile
    profile: {
      title: "Profile",
      welcomeBack: "Welcome back!",
      authenticationRequired: "Authentication Required",
      pleaseLogin: "Please log in to view your profile.",
      goToLogin: "Go to Login",
      totalOrders: "Total Orders",
      completedOrders: "Completed Orders",
      pendingOrders: "Pending Orders",
      totalSpent: "Total Spent",
      orderHistory: "Order History",
      noOrders: "No orders yet",
      date: "Date",
      status: "Status",
      total: "Total",
      viewDetails: "View Details",
      trackOrder: "Track Order",
      shop: "Shop",
      memberSince: "Member Since",
    },
    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      update: "Update",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      clear: "Clear",
      apply: "Apply",
      close: "Close",
      yes: "Yes",
      no: "No",
      confirm: "Confirm",
      back: "Back",
      next: "Next",
      previous: "Previous",
      submit: "Submit",
      view: "View",
      viewAll: "View All",
      actions: "Actions",
      items: "items",
      free: "Free",
      tax: "Tax",
      amount: "Amount",
    },
  },
  am: {
    // Navigation
    nav: {
      home: "መነሻ",
      forYou: "ለእርስዎ",
      newArrivals: "አዲስ ምርቶች",
      popular: "ታዋቂ",
      sale: "ሽያጭ",
      disputes: "ክርክሮች",
      qrScanner: "QR ስካነር",
      categories: "ምድቦች",
      downloadApp: "መተግበሪያ አውርድ",
      support: "ድጋፍ",
      about: "ስለ MegaMart",
      favorites: "የሚወዱ",
      cart: "ጋሪ",
      notifications: "ማሳወቂያዎች",
      profile: "መገለጫ",
      logout: "ውጣ",
      contact: "ነጋዴን ያግኙ",
      becomeSeller: "ነጋዴ ይሁኑ",
      signIn: "ግባ",
      signUp: "ተመዝግብ",
      seller: "ነጋዴ",
      admin: "አስተዳዳሪ",
      allCaughtUp: "ሁሉም ተነባብቷል",
      markAll: "ሁሉንም ምልክት አድርግ",
      unread: "ያልተነበበ",
    },
    // Auth
    auth: {
      welcome: "እንኳን ደህና መጡ",
      megaMart: "MegaMart",
      welcomeSubtitle: "እንኳን ደህና መጡ! እባክዎ መለያዎን ያስገቡ።",
      signInTitle: "ግባ",
      signUpTitle: "እባክዎ የእርስዎን ዝርዝሮች ያስገቡ።",
      email: "ኢሜይል",
      password: "የይለፍ ቃል",
      confirmPassword: "የይለፍ ቃል ያረጋግጡ",
      firstName: "የመጀመሪያ ስም",
      lastName: "የአባት ስም",
      phone: "ስልክ",
      userType: "የተጠቃሚ አይነት",
      buyer: "ገዢ",
      seller: "ነጋዴ",
      agreeTerms: "የአጠቃቀም ውሎችን እቀበላለሁ",
      getNews: "ዜና እና ቅናሾችን ማግኘት እፈልጋለሁ",
      alreadyHaveAccount: "አስቀድመው መለያ አሎት?",
      dontHaveAccount: "መለያ የሎትም?",
      signInHere: "እዚህ ግባ",
      signUpHere: "እዚህ ተመዝግብ",
      developer: "የተገነባ",
      contact: "አገናኝ",
      by: "በ",
    },
    // Home
    home: {
      welcome: "ወደ መደብራችን እንኳን ደህና መጡ",
      discover: "አስደናቂ ምርቶችን በተጣራ ዋጋ ያግኙ",
      shopNow: "አሁን ይግዙ",
      fastShipping: "ፈጣን ማድረስ",
      freeShipping: "ከ$100 በላይ ትዕዛዞች ላይ ነጻ ማድረስ",
      securePayment: "ደህንነቱ የተጠበቀ ክፍያ",
      safePayment: "ደህንነቱ የተጠበቀ የክፍያ ሂደት",
      support24: "24/7 ድጋፍ",
      roundClock: "ሁልጊዜ የደንበኛ ድጋፍ",
    },
    // Products
    products: {
      title: "ምርቶቻችን",
      inStock: "በመጋዘን አለ",
      outOfStock: "በመጋዘን የለም",
      addToCart: "ወደ ጋሪ ጨምር",
      addedToCart: "ወደ ጋሪ ተጨመረ!",
      addToFavorites: "ወደ የሚወዱ ጨምር",
      removeFromFavorites: "ከየሚወዱ አስወግድ",
      freeShipping: "ነጻ ማድረስ",
      easyReturns: "ቀላል መመለስ",
      securePayment: "ደህንነቱ የተጠበቀ ክፍያ",
      price: "ዋጋ",
      quantity: "ብዛት",
      description: "መግለጫ",
      reviews: "ግምገማዎች",
      relatedProducts: "ተዛማጅ ምርቶች",
      noProducts: "ምርት አልተገኘም",
      searchPlaceholder: "ምርቶች፣ የምርት ስም፣ ምድቦችን ፈልግ...",
      filters: "አጣራዎች",
      hideFilters: "አጣራዎችን ደብቅ",
      sort: "ደርድር",
      perPage: "በገጽ",
      inStockOnly: "በመጋዘን ያሉትን ብቻ",
      viewDetails: "ዝርዝሮችን ይመልከቱ",
      saleBadgeShort: "ሽያጭ",
      saleActiveLabel: "የጊዜያዊ ዋጋ",
      newArrival: "አዲስ መጤ",
      sortNewest: "አዲስ የመጣው",
      sortOldest: "አሮጌው",
      sortPriceLow: "ዋጋ: ዝቅተኛ ወደ ከፍ",
      sortPriceHigh: "ዋጋ: ከፍ ወደ ዝቅተኛ",
      sortNameAsc: "ስም: ሀ-ፐ",
      sortNameDesc: "ስም: ፐ-ሀ",
      sortPopular: "ታዋቂ ምርቶች",
      sortSale: "በሽያጭ",
      sortForYou: "ለእርስዎ",
      context: {
        saleTitle: "የተለዩ ቅናሾች",
        saleText: "አሁን በሽያጭ ያሉ የነጋዴዎቻችን ምርቶች እዚህ ናቸው።",
        popularTitle: "ታዋቂ ምርቶች",
        popularText: "በቅርቡ የተገዙ እና የተመለከቱ ምርቶች ዝርዝር።",
        newTitle: "አዲስ መጤዎች",
        newText: "በቅርቡ የተጨመሩ እና በመጋዘን ያሉ ምርቶች።",
        newFallbackText: "በዚህ ሳምንት አዲስ ምርት አልተጨመረም፣ የቅርብ ጊዜ ምርቶችን እያሳየን ነን።",
        forYouTitle: "ለእርስዎ ብቻ",
        forYouText: "ስለ ቅርብ እንቅስቃሴዎ የተገነቡ ምርቶች።",
        forYouFallback: "ልማዶትን ሳንማር ታዋቂ ምርቶችን እዚህ ታያላችሁ።",
      },
    },
    // Cart
    cart: {
      title: "የግዢ ጋሪ",
      empty: "ጋሪዎ ባዶ ነው",
      continueShopping: "ግዢን ይቀጥሉ",
      subtotal: "ንዑስ ጠቅላላ",
      total: "ጠቅላላ",
      checkout: "ወደ ክፍያ ይቀጥሉ",
      remove: "አስወግድ",
      update: "አዘምን",
    },
    // Checkout
    checkout: {
      title: "ክፍያ",
      shippingInfo: "የማድረስ መረጃ",
      paymentMethod: "የክፍያ ዘዴ",
      orderSummary: "የትዕዛዝ ማጠቃለያ",
      placeOrder: "ትዕዛዝ ላክ",
      firstName: "የመጀመሪያ ስም",
      lastName: "የአባት ስም",
      email: "ኢሜይል",
      phone: "ስልክ",
      address: "አድራሻ",
      city: "ከተማ",
      state: "ክልል",
      zipCode: "የፖስታ ኮድ",
      country: "አገር",
      orderNotes: "የትዕዛዝ ማስታወሻዎች",
      paymentInstructions: "የክፍያ መመሪያዎች",
      manualPayment: "እጅ ክፍያ",
      sendPaymentTo: "ክፍያ ወደ ይላኩ",
      enterTransactionId: "ክፍያ ካደረጉ በኋላ የግብይት መለያውን ከዚህ በታች ያስገቡ",
      transactionId: "የግብይት መለያ",
      secureCheckout: "ደህንነቱ የተጠበቀ ክፍያ በSSL ምስጠራ",
      addProductsFirst: "ክፍያ ከመጀመርዎ በፊት ምርቶችን ወደ ጋሪዎ ያክሉ።",
    },
    // Orders
    orders: {
      orderId: "የትዕዛዝ መለያ",
      orderNumber: "የትዕዛዝ ቁጥር",
      orderNumberShort: "ትዕዛዝ #",
      orderDate: "የትዕዛዝ ቀን",
      orderStatus: "የትዕዛዝ ሁኔታ",
      orderDetails: "የትዕዛዝ ዝርዝሮች",
      orderItems: "የትዕዛዝ እቃዎች",
      orderSummary: "የትዕዛዝ ማጠቃለያ",
      shippingAddress: "የመላኪያ አድራሻ",
      orderNotes: "የትዕዛዝ ማስታወሻዎች",
      paymentMethod: "የክፍያ ዘዴ",
      quantity: "ብዛት",
      quantityShort: "ብዛት",
      subtotal: "ንዑስ ድምር",
      tax: "ግብር",
      shipping: "ማድረስ",
      total: "ጠቅላላ",
      downloadReceipt: "ደረሰኝ አውርድ",
      generatingReceipt: "በመዘጋጀት ላይ...",
      continueShopping: "ግዢን ቀጥል",
      viewProfile: "መገለጫ ይመልከቱ",
      viewReceipt: "ደረሰኝ ይመልከቱ",
      emailConfirmation: "በቅርቡ የትዕዛዝ ማረጋገጫ ኢሜይል ይቀበላሉ።",
      confirmedTitle: "ትዕዛዝዎ ተረጋገጠ!",
      confirmedMessage: "ለትዕዛዝዎ እናመሰግናለን። ትዕዛዝዎ ተቀብሎ በማስኬድ ላይ ነው።",
      notFound: "ትዕዛዝ አልተገኘም",
      notFoundDescription: "የሚፈልጉት ትዕዛዝ አይገኝም ወይም ተሰርዟል።",
      goHome: "ወደ መነሻ ተመለስ",
      backToOrders: "ወደ ትዕዛዞች ተመለስ",
      orderTracking: "የትዕዛዝ ክትትል",
      currentStatus: "ወቅታዊ ሁኔታ",
      downloadFailed: "ደረሰኝ መውረድ አልተሳካም። እባክዎ ደግመው ይሞክሩ።",
      viewDetails: "ዝርዝሮችን ይመልከቱ",
      trackOrder: "ትዕዛዝን ይከታተሉ",
      orderIdPrefix: "ትዕዛዝ",
      pending: "በመጠባበቅ ላይ",
      paid: "ተከፍሏል",
      processing: "በማቀናበር ላይ",
      shipped: "ተላከ",
      completed: "ተጠናቋል",
      cancelled: "ተሰርዟል",
      timeline: {
        orderPlaced: "ትዕዛዝ ተገብቷል",
        pending: "በመጠባበቅ ላይ",
        paymentVerified: "ክፍያ ተረጋገጠ",
        processing: "በማቀናበር ላይ",
        shipped: "ተላከ",
        completed: "ተጠናቋል",
        cancelled: "ተሰርዟል",
      },
      paymentMethods: {
        telebirr: "ቴሌብር",
        paypal: "PayPal",
      },
    },
    // Disputes
    disputes: {
      title: "ክርክሮች",
      createDispute: "ክርክር ፍጠር",
      reason: "ምክንያት",
      details: "ዝርዝሮች",
      submit: "ላክ",
      reply: "መልስ",
      status: "ሁኔታ",
      open: "ክፍት",
      accepted: "ተቀባይነት አግኝቷል",
      rejected: "ተቀባይነት አላገኘም",
      resolved: "ተፈትቷል",
      commonReasons: {
        paymentNotApproved: "ክፍያ በጊዜ አልተጸድቀም",
        sellerNotDeliver: "ነጋዴው አልሰጠም",
        wrongItem: "የተሳሳተ ምርት ተቀብሏል",
        missingItem: "ምርት የጠፋ ወይም ያልተሟላ",
        damagedItem: "ምርት የተበላሸ ነው",
        other: "ሌላ",
      },
    },
    // Dashboard
    dashboard: {
      admin: "የአስተዳዳሪ ዳሽቦርድ",
      seller: "የነጋዴ ዳሽቦርድ",
      overview: "አጠቃላይ እይታ",
      users: "ተጠቃሚዎች",
      sellers: "ነጋዴዎች",
      orders: "ትዕዛዞች",
      products: "ምርቶች",
      categories: "ምድቦች",
      brands: "የምርት ስሞች",
      totalRevenue: "ጠቅላላ ገቢ",
      totalOrders: "ጠቅላላ ትዕዛዞች",
      totalProducts: "ጠቅላላ ምርቶች",
      itemsShipped: "የተላኩ ዕቃዎች",
      netEarnings: "ንጹህ ገቢ",
      gross: "ጠቅላላ",
    },
    // Profile
    profile: {
      title: "መገለጫ",
      welcomeBack: "እንኳን ደህና መጡ!",
      authenticationRequired: "ማረጋገጫ ያስፈልጋል",
      pleaseLogin: "መገለጫዎን ለማየት እባክዎ ይግቡ።",
      goToLogin: "ወደ መግቢያ ይሂዱ",
      totalOrders: "ጠቅላላ ትዕዛዞች",
      completedOrders: "የተጠናቀቁ ትዕዛዞች",
      pendingOrders: "በመጠባበቅ ላይ ያሉ ትዕዛዞች",
      totalSpent: "ጠቅላላ የተወጣው",
      orderHistory: "የትዕዛዝ ታሪክ",
      noOrders: "እስካሁን ትዕዛዝ የለም",
      date: "ቀን",
      status: "ሁኔታ",
      total: "ጠቅላላ",
      viewDetails: "ዝርዝሮችን ይመልከቱ",
      trackOrder: "ትዕዛዝን ይከታተሉ",
      shop: "መደብር",
      memberSince: "አባል ከ",
    },
    // Common
    common: {
      loading: "በመጫን ላይ...",
      error: "ስህተት",
      success: "ተሳክቷል",
      save: "አስቀምጥ",
      cancel: "ተወው",
      delete: "ሰርዝ",
      edit: "አርም",
      add: "ጨምር",
      update: "አዘምን",
      search: "ፈልግ",
      filter: "አጣራ",
      sort: "ደርድር",
      clear: "አጽዳ",
      apply: "ተግብር",
      close: "ዝጋ",
      yes: "አዎ",
      no: "አይ",
      confirm: "አረጋግጥ",
      back: "ተመለስ",
      next: "ቀጣይ",
      previous: "ያለፈ",
      submit: "ላክ",
      view: "ይመልከቱ",
      viewAll: "ሁሉንም ይመልከቱ",
      actions: "ድርጊቶች",
      items: "ዕቃዎች",
      free: "ነጻ",
      tax: "ግብር",
      amount: "መጠን",
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState("en");

  useEffect(() => {
    const stored = localStorage.getItem("megamart-language");
    if (stored === "en" || stored === "am") {
      setLanguageState(stored);
      document.documentElement.setAttribute("lang", stored);
      return;
    }
    // Default to browser language or English
    const browserLang = navigator.language.split("-")[0];
    const initial = browserLang === "am" ? "am" : "en";
    setLanguageState(initial);
    localStorage.setItem("megamart-language", initial);
    document.documentElement.setAttribute("lang", initial);
  }, []);

  const setLanguage = useCallback((lang) => {
    if (lang === "en" || lang === "am") {
      setLanguageState(lang);
      localStorage.setItem("megamart-language", lang);
      document.documentElement.setAttribute("lang", lang);
    }
  }, []);

  const t = useCallback(
    (key) => {
      const keys = key.split(".");
      let value = translations[language];
      for (const k of keys) {
        value = value?.[k];
      }
      return value || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
